yui/yuidoc

- lib/server.js
YUIDoc is using `res.send(body, status)` method of Express, but it have been deprecated since Express 4.7.0, and it returns following warning for now. It should use `res.status(status).send(body)` instead.
```
express deprecated res.send(body, status): Use res.status(status).send(body) instead
```
See also: https://github.com/strongloop/express/blob/master/History.md#470--2014-07-25
> Use res.status(status).send(body) instead of res.send(body, status)

- lib/yuidoc.js
It fixes #96. It doesn't have test code by design because mixed newline files in a repository cause confusion.
> Fix a bug with parse files written in CR newline (fixes #96)

- themes/simple/partials/attrs.handlebars
- themes/simple/partials/classes.handlebars
- themes/simple/partials/events.handlebars
- themes/simple/partials/method.handlebars
- themes/simple/partials/module.handlebars
- themes/simple/partials/props.handlebars
> Fix link to source files at simple theme templates

- docs/syntax/index.mustache
- lib/docparser.js
- tests/input/test/test.js
- tests/parser.js
- themes/default/partials/method.handlebars
- themes/simple/partials/method.handlebars
It works similar with the `@return` tag. This means that a type is optional. An actual example is like the following. And, this resolves #135 finally.
```js
/**
* @method getName
* @throws {Error} Throws an exception error.
*/
function getName() {
// do something
}
```
This is a new feature, so I wish I could get any reviewers.
/cc @juandopazo @caridy
> Support @throws tag

- lib/builder.js
- lib/cli.js
- lib/docparser.js
- lib/docview.js
- lib/files.js
- lib/help.js
- lib/index.js
- lib/options.js
- lib/project.js
- lib/server.js
- lib/utils.js
- lib/yuidoc.js
It's existing within the repository. It means we don't need the license information at yuilibrary.com.
> Update the license file URL

- lib/docparser.js
- tests/input/test/test.js
- tests/parser.js
The issue due to non JSDoc tags such as `@media` recognized as JSDoc tags.
It avoid the problem by ignoring tags of the target.
Fix #179.
> Fix a bug with "@" doesn't escapable in example

- docs/args/index.mustache
- lib/builder.js
- package.json
It changes the Markdown parser from marked to markdown-it.
Potential security issues have been reported to the marked, but there is no plan to still be fixed. Because YUIDoc is an one of the development tool, I have thought unlikely to be affected by the problem. However, marked is no longer actively maintained, and I'd like to choice a parser that are more maintenance.
Since YUIDoc only have utilized simply marked as a simple Markdown parser, change can often be reduced.
/cc @juandopazo @caridy
> Change the Markdown parser

- package.json
We're not using any markdown-it plugins, so we don't need to change our source code in YUIDoc.
> Bump markdown-it version to ^4.0.1

- lib/index.js
`util.error` have been deprecated on Node v0.12, but YUI still uses it. It uses `logFn` configuration of YUI to avoid this problem. Basically, it'll uses `console.*` functions instead.
Fix #325.
> Use logFn configuration to logging (fixes #325)

- themes/default/partials/classes.handlebars
- themes/simple/partials/classes.handlebars
This is a same solution with #292 and #302. Fix #323.
> Unindent method Handlebars partials within constructor classes

- lib/builder.js
All descriptions and examples of inherited classes was parsed markdown by markdown-it twice. This fixes #324.
> Fix a bug that inherited class was parsed twice (fixes #324)

- lib/builder.js
This is an additional fixes #324. See also #341.
> Fix @returns tag of extended classes doesn't escape HTML (fixes #324)

- lib/builder.js
- lib/options.js
- lib/project.js
- lib/utils.js
- package.json
The `onevar` and `trailing` rules at JSHint have been removed. I'm not sure we
should use JSCS for now, but these rules doesn't works anymore.
> Drop removed JSHint rules

- lib/builder.js
It turns to `true` the `html` and `linkify` options of `markdown-it`.
This is more similar behavior with the previous Markdown parser. Fixes #344.
> Switch to true Markdown options as default (fixes #344)

- package.json
npm changed to use SPDX to validates the license of npm modules.
* https://github.com/npm/npm/pull/8197
* http://spdx.org/licenses/
> Use SPDX license Identifier in package.json

- lib/docparser.js
Adds tags to suppress warnings on doc build. Can be parsed out as well from json docs
Signed-off-by: Mathew Zummo <mzummo@gmail.com>
> Adds @implements and @interface tags

- lib/builder.js
- package.json
Implements #354.  A utility script is provided to update the native links, which can then be committed to the repo.  In the future, this could be improved to update the links at compile time so that they are always fresh.
> Import utility script for MDN links

- .travis.yml
Added `sude: false` into `.travis.yml` as documented in [the migration guide](http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade) to opt in to the new, container-based, faster builds.
> Upgrade to faster, container-based builds on Travis CI

- .eslintrc
- package.json
* Conform default recommended rules called "eslint:recommended"
* Currently turn off "no-console" rule
See also: http://eslint.org/docs/user-guide/migrating-to-1.0.0
> Bump eslint version to ^1.1.0

- .travis.yml
It changes to testing on Node v4 instead of io.js.
> Travis CI testing on Node v4

- tests/files.js
first argument is either:
* falsey: success scenario
* truthy: failure scenario, and the value may be the error
> [FIX] loosen node-back first-arg check to match node conventions

- lib/cli.js
This PR fixes the `--lint` CLI option by reverting back to the behavior before https://github.com/yui/yuidoc/pull/348. This resolves https://github.com/yui/yuidoc/issues/403.
/cc @stefanpenner
> Fix "--lint" option

- package.json
https://nodesecurity.io/advisories/118
> [fixes #118] bump minimatch to v3.0.2

- conf/docs/layouts/main.mustache
This trivial PR changes the PNG build status badge to a SVG build status badge.
> Travis build status badge as SVG

- .travis.yml
* Add testing on Node.js v6
* Add testing on Node.js v7 with allow_failures flag
* Drop testing on Node.js v0.10 and v0.12
> CI building updates

- lib/builder.js
- output/api/files/lib_builder.js.html
- tests/builder.js
- tests/input/inherit/examplemodule.js
`extension_for` blocks are never showing up. This is because there's a typo
error on `lib/builder.js`.
`entension_for` is wrong, replaced with `extension_for` instead.
> Fixed typo error
